spring.main.web-application-type: none
app:
  print-schedule: "*/10 * * * * *"
  order-api:
    base-uri: "http://localhost:8080"
  print-server:
    host: "localhost"
    username: "root"
    private-key-path: "./private.key"
    printer-path: "/print/"
